### ISSUE TITLE
Inclusion of a new paper

### ISSUE THREAD

**Issue by ragatti** [hubertjb/dl-eeg-review#5]
[Prediction of Hand Movement Speed and Force from Single-trial EEG with Convolutional Neural Networks](https://doi.org/10.1101/492660)
Ramiro Gatti, Yanina Atum, Luciano Schiaffino, Mads Jochumsen, and José Biurrun Manresa
2018

**Comment by agramfort** [comment]
Was this done ?

**Comment by ragatti** [comment]
Hi, not yet. But I will try to submit it as a New Reviewed Paper by email or PR.
